wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: AAAI26
  mode: 'online'
  save_dir: ${hydra:run.dir}
  name: ${tag}_${datamodule.params_data.name}_${datamodule.params_data.task}_mr${datamodule.params_data.missing_rate}_pn${datamodule.params_data.patch_num}_${model.params_model.name}_hidden${model.params_model.hidden_size}_latent${model.params_model.latent_num}_TM-${model.params_model.token_Mixer}
