_target_: models.model_interface.MIONetModule
params_model:
  name: MIONET
  activation: 'relu'
  initializer: 'default'
  input_channel: 10
  space_dim:  ${datamodule.space_dim}
  missing_rate: ${datamodule.missing_rate}
params_optim: ${optim}
params_scheduler: ${scheduler}
