_target_: model_interface.MIONetModule
params_model:
  name: MIONet
  activation: 'relu'
  initializer: 'default'
  input_size: 10
  space_dim:  ${datamodule.space_dim}
  space_size: [64, 64]
  missing_rate: ${datamodule.missing_rate}
  ref: 8
  ntrain: ${datamodule.n_train_test[0]}
  ntest: ${datamodule.n_train_test[1]}
params_optim: ${optim}
params_scheduler: ${scheduler}