_target_: model_interface.OFormerFillGapModule
params_model:
  name: OFORMER_FILLGAP
  in_channels: 12
  encoder_emb_dim: 64
  out_seq_emb_dim: 128
  encoder_heads: 1
  encoder_depth: 5
  decoder_emb_dim: 256
  out_channels: 1
  out_step: 1
  propagator_depth: 1
  fourier_frequency: 8
  is_fillGap: True
  sigma: 1.
  ntrain: ${datamodule.n_train_test[0]}
  ntest:  ${datamodule.n_train_test[1]}
params_optim: ${optim}
params_scheduler: ${scheduler}
