_target_: model_interface_irregular.OursModule
params_model:
  name: Ours_irregular
  input_size: 2
  output_size: 1
  ntrain: ${datamodule.n_train_test[0]}
  ntest:  ${datamodule.n_train_test[1]}
  scale_factor: 2.
  space_size: ${datamodule.space_size}
  ref: 0
  hidden_size: 128
  head_size: 16
  heads_num: 8
  kernel_layers: 8
  feature_basis_num: 64
  alpha: 1e-4
  t: 
  downsample: ${datamodule.downsample}
  monitor: train/full_loss

params_optim: ${optim}

params_scheduler: ${scheduler}