defaults:
  - _self_
  - hydra:      default   # ResMLP SirenNet FFN_P FFN_G MMGNet
  - datamodule: ns_v-5    # gst sst
  - model:      FNO       # ResMLP SirenNet FFN_P FFN_G MMGNet
  - optim:      default
  - scheduler:  default
  - callback:   default
  - logger:     wandb
  - trainer:    default

seed: 123456
sound: minuet
tag:
bark_url: https://api.day.app/jxjT44t4wHkyz3dj8u5erE/
