defaults:
  - _self_
  - hydra:      default
  - datamodule: ns
  - model:      FNO
  - optim:      default
  - scheduler:  default
  - callback:   default
  - logger:     wandb
  - trainer:    default

seed: 123456
sound: minuet
tag:
bark_url: https://api.day.app/jxjT44t4wHkyz3dj8u5erE/
