_target_:     dataloaders.data_interface.ELAS_DataModule
name:         elasticity
data_dir:     /root/data/elas
task:         task3
missing_rate: 0.5
n_train_test: [1000, 200] # sst shape   (366, 901, 1001)
b_train_test: [2, 2]
num_workers:  2
space_dim:    2 
space_size:   
downsample:
T_all:
