_target_:     dataloaders.data_interface.ERA5_DataModule
params_data:
  name:         ERA5
  data_dir:     /root/data/WeatherBench/2m_temperature_18-25.grib
  task:         task3
  missing_rate: 0.5
  n_train_test: [300, 50] # sst shape   (366, 901, 1001)
  b_train_test: [2, 2]
  num_workers:  2
  space_size:   [720, 1440]
  space_dim:    2
  T_all:        14
  downsample:   8
  patch_size:   6
  patch_num:    [15, 30]
  ref:          ${model.params_model.ref}
