_target_:     dataloaders.data_interface.NS_DataModule
name:         NS_v-5
data_dir:     /root/data/NavierStokes_V1e-5_N1200_T20.mat
task:         task1
missing_rate: 0.5
n_train_test: [1000, 200] # sst shape   (366, 901, 1001)
b_train_test: [10, 10]
num_workers:  4
space_size:   [64, 64]
space_dim:    2
T_all:        20
downsample:   1
ref:          ${model.params_model.ref}
