_target_:     dataloaders.data_interface.NS_DataModule
name:         NS_v-5
data_dir:     /root/data/NavierStokes_V1e-5_N1200_T20.mat
task:         task1
missing_rate: 0.5 # [0.05, 0.05] [0.25, 0.25] [0.5, 0.5]
n_train_test: [1000, 200] # sst shape   (366, 901, 1001)
b_train_test: [12, 12]
num_workers:  4
space_dim:    [64, 64]
T_all:        20